config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #devise_for :sessions
  resources :docs
  authenticated :user do
    root "docs#index", as:"authenticated_route"
  end
  get 'welcome/index'
  
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bubble.rb
class Bubble < ApplicationRecord
end

app/models/doc.rb
class Doc < ActiveRecord::Base
    belongs_to :user
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bubbles_controller.rb
class BubblesController < ApplicationController
  before_action :set_bubble, only: [:show, :edit, :update, :destroy]

  # GET /bubbles
  # GET /bubbles.json
  def index
    @bubbles = Bubble.all
  end

  # GET /bubbles/1
  # GET /bubbles/1.json
  def show
  end

  # GET /bubbles/new
  def new
    @bubble = Bubble.new
  end

  # GET /bubbles/1/edit
  def edit
  end

  # POST /bubbles
  # POST /bubbles.json
  def create
    @bubble = Bubble.new(bubble_params)

    respond_to do |format|
      if @bubble.save
        format.html { redirect_to @bubble, notice: 'Bubble was successfully created.' }
        format.json { render :show, status: :created, location: @bubble }
      else
        format.html { render :new }
        format.json { render json: @bubble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bubbles/1
  # PATCH/PUT /bubbles/1.json
  def update
    respond_to do |format|
      if @bubble.update(bubble_params)
        format.html { redirect_to @bubble, notice: 'Bubble was successfully updated.' }
        format.json { render :show, status: :ok, location: @bubble }
      else
        format.html { render :edit }
        format.json { render json: @bubble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bubbles/1
  # DELETE /bubbles/1.json
  def destroy
    @bubble.destroy
    respond_to do |format|
      format.html { redirect_to bubbles_url, notice: 'Bubble was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bubble
      @bubble = Bubble.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bubble_params
      params.fetch(:bubble, {})
    end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
 before_action :find_doc, only: [:show, :edit, :update, :destroy]

    def index
        @docs = Doc.where(user_id: current_user)
    end

    def show
    end

    def new
        before_action :authenticate_user!, only: [:new,:create]
        @doc = current_user.docs.build
    end

    def create
        @doc = current_user.docs.build(doc_params)

        if @doc.save
            redirect_to @doc
            #Refreshes the HTTPS file. Lose all content entered.
        else
            render 'new'
            #Second chance in saving content. Does not refresh.
        end
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private

    def find_doc
        @doc = Doc.find(params[:id])
    end

    def doc_params
        params.require(:doc).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bubbles_helper.rb
module BubblesHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bubbles/_form.html.erb
<%= form_with(model: bubble, local: true) do |form| %>
  <% if bubble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bubble.errors.count, "error") %> prohibited this bubble from being saved:</h2>

      <ul>
        <% bubble.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bubbles/edit.html.erb
<h1>Editing Bubble</h1>

<%= render 'form', bubble: @bubble %>

<%= link_to 'Show', @bubble %> |
<%= link_to 'Back', bubbles_path %>

app/views/bubbles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bubbles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bubbles.each do |bubble| %>
      <tr>
        <td><%= link_to 'Show', bubble %></td>
        <td><%= link_to 'Edit', edit_bubble_path(bubble) %></td>
        <td><%= link_to 'Destroy', bubble, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bubble', new_bubble_path %>

app/views/bubbles/new.html.erb
<h1>New Bubble</h1>

<%= render 'form', bubble: @bubble %>

<%= link_to 'Back', bubbles_path %>

app/views/bubbles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bubble_path(@bubble) %> |
<%= link_to 'Back', bubbles_path %>

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :context
  -#Why does my form only show with "context" and not "content"...?
  = f.button :submit, class: "button"

app/views/docs/edit.html.haml
.wrapper_with_padding
    %h1 Edit your Doc

    = render "form"

    = link_to "Cancel", doc_path

app/views/docs/index.html.haml
.wrapper_with_padding
    #docs.clearfix
    - unless @docs.blank?
        - @docs.each do |doc|
            %a( href: (url_for [doc]))
                .doc
                    %p.title= doc.title
                    %p.date= time_ago_in_words(doc.created_at)
                    %p.content= truncate(doc.context, length:50)
        - else
            %h2 Create Doc
            %p Tell your secret. It's safe with us.
            %button= link_to "Create Doc", new_doc_path

 = link_to "Create New Doc", new_doc_path

app/views/docs/new.html.haml
.wrapper_with_padding
    %h1 new document? drop it here

    = render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
    #doc_show
        %h1.title= @doc.title
        %p= @doc.context

        .buttons
            = link_to "Fix Doc", edit_doc_path(@doc), class: "button"
            = link_to "Trash Doc", doc_path(@doc), method: :delete, data: { confirm: "Destroy this secret doc?" }, class: "button"
            = link_to "All Docs", docs_path

app/views/layouts/application.html.haml
!!! 
%html
%head
    %title FileCab | Store your secrets.
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_pack_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
%body
    %header
    .header_inner
    = link_to "FileCabinet", root_path, id: "logo"

    %nav
    - if user_signed_in?
        = link_to "Create Doc", new_doc_path
        = link_to "Sign Out", destroy_user_session_path, method: :delete

    - else
        = link_to "Log In", new_user_session_path

    %p.notice = notice
    %p.alert = alert 

    = yield

app/views/welcome/index.html.haml
#banner
.banner_content
%h1 Welcome to FileCab.
%p Keep your secrets safe in this obscure Google Docs like web app.
%button= link_to "Enter", new_user_registration_path

#callouts
    .callout_inner
        .wrapper
            .callout
            %h2 Organize
            %p Here you can organize your stuff here. I suck at typing properly.

#bottom_cta
    .wrapper
        %h2 Stay Secured.
        %br
        %button= link_to "Join Now", new_user_registration_path